/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 101
#define YY_END_OF_BUFFER 102
static yyconst short int yy_acclist[374] =
    {   0,
       10,   10,    1,  102,  100,  101,    4,  100,  101,   44,
      101,    3,  100,  101,  100,  101,   75,  100,  101,   25,
      100,  101,  100,  101,   74,  100,  101,   60,  100,  101,
       61,  100,  101,   33,  100,  101,   31,  100,  101,   66,
      100,  101,   32,  100,  101,   26,  100,  101,   34,  100,
      101,   70,  100,  101,   70,  100,  101,   27,  100,  101,
       67,  100,  101,   36,  100,  101,   28,  100,  101,   37,
      100,  101,   69,  100,  101,   69,  100,  101,   69,  100,
      101,   69,  100,  101,   69,  100,  101,   69,  100,  101,
       69,  100,  101,   62,  100,  101,   29,  100,  101,   63,

      100,  101,   35,  100,  101,   68,  100,  101,   68,  100,
      101,   68,  100,  101,   68,  100,  101,   68,  100,  101,
       68,  100,  101,   68,  100,  101,   68,  100,  101,   68,
      100,  101,   68,  100,  101,   64,  100,  101,   30,  100,
      101,   65,  100,  101,   79,  100,  101,   82,  101,   81,
      100,  101,   80,  100,  101,   78,  100,  101,   99,  100,
      101,  101,   92,   99,  100,  101,   91,   99,  100,  101,
       90,   95,   99,  100,  101,   95,   99,  100,  101,   94,
       99,  100,  101,   93,   99,  100,  101,   99,  100,  101,
       86,   99,  100,  101,   87,   99,  100,  101,   88,   99,

      100,  101,   83,   99,  100,  101,   99,  100,  101,   85,
       99,  100,  101,   84,   99,  100,  101,   89,   99,  100,
      101,   99,  100,  101,    7,  100,  101,    6,  101,   10,
      100,  101,   10,  101,   11,  100,  101,   43,  100,  101,
       43,  100,  101,   43,  101,   42,  100,  101,    2,  100,
      101,    1,    2,  100,  101,    1,  101,    4,   44,   44,
        3,   22,   20,   24,    5,   12,   17,   70,   15,   13,
       18,   16,   14,   19,   69,   69,   69,   69,   69,   69,
       69,   69,   23,   68,   68,   68,   40,   68,   68,   48,
       68,   45,   68,   68,   41,   68,   68,   68,   68,    8,

       21,   79,   76,   95,   98,   96,   97,    7,   10,   11,
       11,    9,   43,   43,   42,    1,   73,   72,   71,   69,
       69,   69,   69,   52,   69,   69,   69,   68,   68,   68,
       38,   68,   68,   68,   68,   77,   57,   69,   54,   69,
       69,   69,   69,   69,   58,   69,   47,   68,   51,   68,
       50,   68,   68,   49,   68,   68,   73,   59,   69,   56,
       69,   69,   69,   68,   39,   68,   69,   55,   69,   46,
       68,   53,   69
    } ;

static yyconst short int yy_accept[206] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    3,    3,    3,    3,    4,    5,    7,   10,
       12,   15,   17,   20,   23,   25,   28,   31,   34,   37,
       40,   43,   46,   49,   52,   55,   58,   61,   64,   67,
       70,   73,   76,   79,   82,   85,   88,   91,   94,   97,
      100,  103,  106,  109,  112,  115,  118,  121,  124,  127,
      130,  133,  136,  139,  142,  145,  148,  150,  153,  156,
      159,  162,  163,  167,  171,  176,  180,  184,  188,  191,
      195,  199,  203,  207,  210,  214,  218,  222,  225,  228,
      230,  233,  235,  238,  241,  244,  246,  249,  252,  256,

      258,  259,  260,  261,  262,  263,  264,  265,  266,  267,
      268,  268,  269,  269,  269,  270,  271,  272,  273,  274,
      275,  276,  277,  278,  279,  280,  281,  282,  283,  284,
      285,  286,  287,  289,  290,  292,  294,  295,  297,  298,
      299,  300,  301,  302,  303,  303,  304,  305,  306,  307,
      308,  309,  310,  311,  312,  313,  314,  315,  316,  317,
      318,  319,  320,  321,  322,  323,  324,  326,  327,  328,
      329,  330,  331,  333,  334,  335,  336,  337,  337,  339,
      341,  342,  343,  344,  345,  347,  349,  351,  353,  354,
      356,  357,  357,  358,  360,  362,  363,  364,  365,  367,

      368,  370,  372,  374,  374
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    1,    8,    1,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   29,   32,   33,
       34,   34,   35,   34,   34,   34,   34,   34,   36,   34,
       34,   34,   37,   38,   34,   34,   34,   39,   34,   34,
       40,   41,   42,   43,   44,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,   54,   54,   55,   54,   56,
       57,   54,   54,   58,   59,   60,   61,   62,   63,   64,
       54,   54,   65,   66,   67,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[68] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    4,
        1,    1,    1,    1,    1,    5,    1,    1,    6,    6,
        6,    1,    1,    1,    1,    1,    1,    7,    8,    8,
        8,    8,    8,    9,    9,    9,    9,    9,    9,    7,
       10,    7,    7,    9,    6,    6,    6,    6,    6,    6,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,    1,    1,    1
    } ;

static yyconst short int yy_base[221] =
    {   0,
        0,    0,   65,   66,   67,   75,  114,  176,  382,  379,
       68,   76,   78,   84,  377,   88,  377,  452,  372,   92,
      367,  297,  452,  452,  293,  452,  452,  452,  288,  452,
      452,   72,  452,  275,   83,   92,  277,  452,   80,   89,
      273,    0,  240,  244,   65,  239,  234,  235,  452,  452,
      452,  249,    0,  246,   73,  235,   73,  240,  238,  238,
      234,  233,  268,  217,  452,    0,  452,  452,  452,  134,
      452,  452,  452,  452,  106,  125,  452,  452,    0,  452,
      452,  452,  452,  112,  452,  452,  452,    0,    0,  452,
        0,    0,   83,  452,  149,  160,  452,  452,  164,  179,

      280,  185,  189,  276,  452,  452,  452,  452,  452,  452,
      179,  185,  188,    0,  452,  452,  452,  452,  452,  452,
        0,  222,  233,  222,  219,  215,  216,  212,  452,    0,
      213,  211,    0,  211,    0,    0,  202,    0,  201,  208,
      207,  452,  452,    0,  207,  452,  208,  452,  196,    0,
        0,    0,  126,  157,  452,  452,  239,  452,  244,  231,
      211,    0,  199,  187,  184,  194,  188,  182,  174,  171,
      173,  164,    0,  140,  133,  127,  452,  239,    0,    0,
      131,  117,  117,  105,    0,    0,    0,    0,  100,    0,
      107,  245,  248,    0,    0,  104,   97,   72,    0,   43,

        0,    0,    0,  452,  304,  315,  326,  337,  348,  359,
      367,  375,  386,  391,  396,  404,  415,  426,  437,  443
    } ;

static yyconst short int yy_def[221] =
    {   0,
      204,    1,  205,  205,  205,  205,  206,  206,  207,  207,
      208,  208,  209,  209,  210,  210,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  211,  211,  211,  211,  211,  211,  211,  204,  204,
      204,  204,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  204,  204,  204,  213,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  214,  204,
      204,  204,  204,  204,  204,  204,  204,  215,  216,  204,
      217,  217,  218,  204,  219,  219,  204,  204,  204,  204,

      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  220,  204,  204,  204,  204,  204,  204,
      211,  211,  211,  211,  211,  211,  211,  211,  204,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  204,  204,  213,  204,  204,  204,  204,  204,  215,
      216,  217,  218,  218,  204,  204,  219,  204,  204,  204,
      204,  220,  211,  211,  211,  211,  211,  211,  211,  212,
      212,  212,  212,  212,  212,  212,  204,  204,  211,  211,
      211,  211,  211,  211,  211,  212,  212,  212,  212,  212,
      212,  204,  204,  211,  211,  211,  211,  212,  212,  211,

      211,  212,  211,    0,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204
    } ;

static yyconst short int yy_nxt[520] =
    {   0,
       18,   19,   20,   18,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       36,   37,   38,   39,   40,   41,   18,   18,   42,   43,
       44,   42,   45,   42,   46,   42,   47,   48,   42,   49,
       50,   51,   52,   53,   53,   53,   54,   55,   56,   53,
       53,   53,   57,   53,   58,   53,   59,   60,   53,   61,
       53,   53,   62,   53,   63,   64,   65,   67,   67,   67,
       92,   68,   68,   68,   69,   69,   69,   67,   92,   95,
       96,   68,   95,   93,   69,   95,   96,  108,   95,   99,
      100,   93,   99,  102,  103,  116,  102,  109,  154,  111,

      203,  112,  112,  112,  117,   70,   70,   70,  111,  124,
      112,  112,  112,  118,  119,   70,   72,  132,  113,  125,
       73,  114,  135,   74,  147,  147,  147,  202,  136,  133,
      149,  149,   75,   76,   76,  145,  145,  145,  145,  113,
       77,  204,   97,  147,  147,  147,  114,  201,   97,  155,
      157,  157,  200,  157,   78,  199,   79,  198,   80,   81,
      197,  157,  157,   82,  157,  159,  159,  196,  159,   83,
       84,   85,  154,   86,  146,   87,  195,   88,   72,  194,
      159,  159,   73,  159,  191,   74,  102,  102,  190,  102,
      102,  103,  204,  102,   75,   76,   76,  160,  160,  160,

      189,  111,   77,  112,  112,  112,  161,  161,  145,  145,
      145,  145,  188,  158,  149,  149,   78,  187,   79,  186,
       80,   81,  185,  155,  158,   82,  147,  147,  147,  161,
      161,   83,   84,   85,  184,   86,  183,   87,  182,   88,
      157,  157,  181,  157,  180,  159,  159,  177,  159,  160,
      160,  160,  192,  179,  192,  176,  175,  193,  193,  193,
      174,  173,  178,  193,  193,  193,  193,  193,  193,  172,
      171,  170,  169,  168,  167,  166,  165,  164,  163,  178,
      104,  101,  143,  142,  141,  140,  139,  138,  137,  134,
      131,  129,  128,  127,  126,  123,  122,  120,  115,  110,

      107,  106,  105,  158,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
      121,  104,  121,  101,  121,  121,  204,  121,  130,   72,
      130,   90,  130,  130,   90,  130,  144,  204,  204,  204,
      144,  144,  144,  144,  144,  204,  144,  148,  148,  148,

      148,  150,  204,  150,  151,  204,  151,  151,  151,  151,
      151,  151,  151,  151,  151,  152,  152,  152,  152,  204,
      152,  152,  152,  152,  152,  152,  153,  153,  153,  153,
      153,  153,  153,  153,  153,  153,  153,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  162,  204,
      162,   17,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,

      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204
    } ;

static yyconst short int yy_chk[520] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    5,
       11,    3,    4,    5,    3,    4,    5,    6,   12,   13,
       13,    6,   13,   11,    6,   14,   14,   32,   14,   16,
       16,   12,   16,   20,   20,   39,   20,   32,   93,   35,

      200,   35,   35,   35,   39,    3,    4,    5,   36,   45,
       36,   36,   36,   40,   40,    6,    7,   55,   35,   45,
        7,   35,   57,    7,   75,   75,   75,  198,   57,   55,
       84,   84,    7,    7,    7,   70,   70,   70,   70,   35,
        7,  153,   13,   76,   76,   76,   35,  197,   14,   93,
       95,   95,  196,   95,    7,  191,    7,  189,    7,    7,
      184,   96,   96,    7,   96,   99,   99,  183,   99,    7,
        7,    7,  154,    7,   70,    7,  182,    7,    8,  181,
      100,  100,    8,  100,  176,    8,  102,  102,  175,  102,
      103,  103,  153,  103,    8,    8,    8,  111,  111,  111,

      174,  112,    8,  112,  112,  112,  113,  113,  145,  145,
      145,  145,  172,   95,  149,  149,    8,  171,    8,  170,
        8,    8,  169,  154,   96,    8,  147,  147,  147,  161,
      161,    8,    8,    8,  168,    8,  167,    8,  166,    8,
      157,  157,  165,  157,  164,  159,  159,  145,  159,  160,
      160,  160,  178,  163,  178,  141,  140,  178,  178,  178,
      139,  137,  160,  192,  192,  192,  193,  193,  193,  134,
      132,  131,  128,  127,  126,  125,  124,  123,  122,  160,
      104,  101,   64,   63,   62,   61,   60,   59,   58,   56,
       54,   52,   48,   47,   46,   44,   43,   41,   37,   34,

       29,   25,   22,  157,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      211,   21,  211,   19,  211,  211,   17,  211,  212,   15,
      212,   10,  212,  212,    9,  212,  213,    0,    0,    0,
      213,  213,  213,  213,  213,    0,  213,  214,  214,  214,

      214,  215,    0,  215,  216,    0,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  217,  217,  217,  217,    0,
      217,  217,  217,  217,  217,  217,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  219,  219,  219,
      219,  219,  219,  219,  219,  219,  219,  219,  220,    0,
      220,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,

      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#define INITIAL 0
#line 2 "lex.l"
#include <iostream>
#include <stack>
#include <vector>
#include <string>
#include <cstdlib>
#include <cstdio>
#include <deque>
#include "token_queue.h"
#include "parser.tab.h"

using namespace std;

int last_pushed_token_type;
void push_token(int type, const string& text);
void lexical_error(const char* message, const char* value);
int count_last_line_indent(const char* text); 
bool process_indentation(const char* line_text, vector<int>& layout_stack, bool start_block_flag, bool first_block_indent_flag, bool end_of_file_flag);
void place_semicolons(const char* line_text, int first_indent, bool end_of_file_flag);
#define STRING 1
#define CHAR 2
#define ESCAPE 3
#define COMMENT 4
#define MULTILINE_COMMENT 5
#define AFTER_KEYWORD 6
#define FIRST_LINE 7

#define YY_NEVER_INTERACTIVE 1
#line 632 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 39 "lex.l"



string string_buffer;        // для строковых литералов
bool is_char_escape;         // флаг для определения типа escape-последовательности
string comment_buffer;	     // для комментариев
int comment_nest_level = 0;  // для отслеживания вложенности комментариев
bool char_processed = false; // для отслеживания обработки char
vector<int> layout_stack = {0};   // стек с количествами отступов  
bool indent_process_flag = false; // флаг обработки отступов в блоках
int first_indent = 0;		          // количество отступов первой строки
bool first_line_flag = true;      // флаг необходимости обработки первой строки отдельно
int brace_count = 0;		          // счетчик для баланса фигурных скобок
bool first_block_indent_flag = false;
bool custom_indents_in_block_flag = false; // флаг пропуска блока с пользовательскими отступами


	/* Проверяем, находимся ли мы в начале файла */
	if (first_line_flag) {
		first_line_flag = false;
		BEGIN(FIRST_LINE);
	}
	
#line 810 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 205 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 452 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */

case 1:
YY_RULE_SETUP
#line 63 "lex.l"
{ first_indent = count_last_line_indent(yytext); 
				  BEGIN(INITIAL); 
				}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 67 "lex.l"
{ 
				yyless(0);
				first_indent = 0;
				BEGIN(INITIAL);
				}
	YY_BREAK

case 3:
YY_RULE_SETUP
#line 74 "lex.l"
{ /* Пропускаем пробелы */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 75 "lex.l"
{  /* Пропускаем табы */ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 77 "lex.l"
{
                  // Однострочный комментарий
                  comment_buffer.clear();
                  comment_buffer = "--";
                  BEGIN(COMMENT);
                }
	YY_BREAK

case 6:
YY_RULE_SETUP
#line 85 "lex.l"
{ 
				  yyless(0);
                  //push_token(SINGLELINE_COMMENT, comment_buffer);
                  BEGIN(INITIAL); 
                }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 90 "lex.l"
{ 
                  comment_buffer += yytext;
                }
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 93 "lex.l"
{
                  //push_token(SINGLELINE_COMMENT, comment_buffer);
                  BEGIN(INITIAL);
                }
	YY_BREAK

case 8:
YY_RULE_SETUP
#line 99 "lex.l"
{ 
                  // Начало многострочного комментария
                  comment_nest_level = 1;
                  comment_buffer.clear();
                  comment_buffer = "{-";
                  BEGIN(MULTILINE_COMMENT);
                }
	YY_BREAK

case 9:
YY_RULE_SETUP
#line 108 "lex.l"
{ 
                  comment_buffer += yytext;
                  push_token(MULTILINE_COMMENT, comment_buffer);
                  BEGIN(INITIAL);
                }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 114 "lex.l"
{ comment_buffer += yytext; } 
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 115 "lex.l"
{ comment_buffer += yytext; }
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 117 "lex.l"
{ 
                  lexical_error("Unterminated multiline comment", comment_buffer.c_str());
			   BEGIN(INITIAL);
                }
	YY_BREAK

case 12:
YY_RULE_SETUP
#line 123 "lex.l"
{ push_token(RIGHT_ARROW, yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 124 "lex.l"
{ push_token(LEFT_ARROW, yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 125 "lex.l"
{ push_token(FAT_ARROW, yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 126 "lex.l"
{ push_token(DOUBLE_COLON, yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 127 "lex.l"
{ push_token(DOUBLE_EQUALS, yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 128 "lex.l"
{ push_token(NOT_EQUALS, yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 129 "lex.l"
{ push_token(LESS_EQUAL, yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 130 "lex.l"
{ push_token(GREATER_EQUAL, yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 131 "lex.l"
{ push_token(DOUBLE_AMPERSAND, yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 132 "lex.l"
{ push_token(DOUBLE_PIPE, yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 133 "lex.l"
{ push_token(DOUBLE_BANG, yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 134 "lex.l"
{ push_token(DOUBLE_CARET, yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 135 "lex.l"
{ push_token(DOUBLE_ASTERISK, yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 136 "lex.l"
{ push_token(DOLLAR, yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 137 "lex.l"
{ push_token(DOT, yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 138 "lex.l"
{ push_token(COLON, yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 139 "lex.l"
{ push_token(EQUALS, yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 140 "lex.l"
{ push_token(BACKSLASH, yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 141 "lex.l"
{ push_token(PIPE, yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 142 "lex.l"
{ push_token(PLUS, yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 143 "lex.l"
{ push_token(MINUS, yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 144 "lex.l"
{ push_token(ASTERISK, yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 145 "lex.l"
{ push_token(SLASH, yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 146 "lex.l"
{ push_token(CARET, yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 147 "lex.l"
{ push_token(LESS, yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 148 "lex.l"
{ push_token(GREATER, yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 150 "lex.l"
{ push_token(KW_LET, yytext); BEGIN(AFTER_KEYWORD);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 151 "lex.l"
{ push_token(KW_WHERE, yytext); BEGIN(AFTER_KEYWORD);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 152 "lex.l"
{ push_token(KW_DO, yytext); BEGIN(AFTER_KEYWORD);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 153 "lex.l"
{ push_token(KW_OF, yytext); BEGIN(AFTER_KEYWORD);}
	YY_BREAK

case 42:
YY_RULE_SETUP
#line 156 "lex.l"
{
				 yyless(0);
				 indent_process_flag = false;
				 custom_indents_in_block_flag = true;
				 BEGIN(INITIAL);
				}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 162 "lex.l"
{
				 yyless(0);
				 indent_process_flag = true;
				 custom_indents_in_block_flag = false;
				 process_indentation(yytext, layout_stack, true, first_block_indent_flag, false);
				 first_block_indent_flag = true;
				 BEGIN(INITIAL);
				}
	YY_BREAK

case 44:
YY_RULE_SETUP
#line 172 "lex.l"
{
				if (indent_process_flag && !custom_indents_in_block_flag){
					indent_process_flag = process_indentation(yytext, layout_stack, false, first_block_indent_flag, false);
					first_block_indent_flag = false;
				} else if (!custom_indents_in_block_flag){
					place_semicolons(yytext, first_indent, false);
				}
            }
	YY_BREAK

case YY_STATE_EOF(INITIAL):
#line 182 "lex.l"
{
				if (indent_process_flag && !custom_indents_in_block_flag){
					while (indent_process_flag){
						indent_process_flag = process_indentation(yytext, layout_stack, false, first_block_indent_flag, true);
						first_block_indent_flag = false;
					}
				} else if (!custom_indents_in_block_flag){
					place_semicolons(yytext, first_indent, true);
				}
				
				if (brace_count != 0){
					lexical_error("Mismatched brackets", yytext);
				}
				return 0;
           }
	YY_BREAK

case 45:
YY_RULE_SETUP
#line 199 "lex.l"
{ push_token(KW_IN, yytext); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 200 "lex.l"
{ push_token(KW_RETURN, yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 201 "lex.l"
{ push_token(KW_CASE, yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 202 "lex.l"
{ push_token(KW_IF, yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 203 "lex.l"
{ push_token(KW_THEN, yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 204 "lex.l"
{ push_token(KW_ELSE, yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 205 "lex.l"
{ push_token(KW_DATA, yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 207 "lex.l"
{ push_token(KW_INT, yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 208 "lex.l"
{ push_token(KW_INT, yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 209 "lex.l"
{ push_token(KW_CHAR, yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 210 "lex.l"
{ push_token(KW_STRING, yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 211 "lex.l"
{ push_token(KW_FLOAT, yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 212 "lex.l"
{ push_token(KW_BOOL, yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 213 "lex.l"
{ push_token(KW_TRUE, yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 214 "lex.l"
{ push_token(KW_FALSE, yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 216 "lex.l"
{ push_token(LEFT_PAREN, yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 217 "lex.l"
{ push_token(RIGHT_PAREN, yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 218 "lex.l"
{ push_token(LEFT_BRACKET, yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 219 "lex.l"
{ push_token(RIGHT_BRACKET, yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 220 "lex.l"
{ 
                 brace_count++;
                 push_token(LEFT_BRACE, yytext);
               }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 224 "lex.l"
{ 
                 brace_count--;
				 if (brace_count == 0){
					custom_indents_in_block_flag = false;
				 }
                 push_token(RIGHT_BRACE, yytext);
               }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 231 "lex.l"
{ push_token(COMMA, yytext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 232 "lex.l"
{ if (last_pushed_token_type != SEMICOLON) push_token(SEMICOLON, yytext); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 234 "lex.l"
{ push_token(ID, yytext); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 235 "lex.l"
{ push_token(ID_CAP, yytext); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 237 "lex.l"
{ push_token(DEC_LITERAL, yytext); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 238 "lex.l"
{ push_token(HEX_LITERAL, yytext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 239 "lex.l"
{ push_token(OCT_LITERAL, yytext+2); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 240 "lex.l"
{ push_token(FLOAT, yytext); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 242 "lex.l"
{ string_buffer.clear(); is_char_escape = true; BEGIN(CHAR); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 243 "lex.l"
{ string_buffer.clear(); is_char_escape = false; BEGIN(STRING); }
	YY_BREAK

case 76:
YY_RULE_SETUP
#line 246 "lex.l"
{
				/* Экранированный бекслеш */
				string_buffer += '\\';
			}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 251 "lex.l"
{
						/* Haskell string gap: backslash + whitespace 
						(включая перевод строки) + backslash */
						/* Игнорируем — ничего не добавляем в строку */
					}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 257 "lex.l"
{ BEGIN(ESCAPE); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 259 "lex.l"
{ string_buffer += yytext; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 261 "lex.l"
{ 
            if (is_char_escape) {
                if (string_buffer.size() != 1) 
                    lexical_error("Invalid char literal length", string_buffer.c_str());
                push_token(CHAR_LITERAL, string_buffer);
                string_buffer.clear();
                BEGIN(INITIAL);
            } else {
                string_buffer += '\''; // обычный символ внутри строки
            }
          }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 273 "lex.l"
{ 
            if (!is_char_escape) {
                push_token(STRING_LITERAL, string_buffer);
                string_buffer.clear();
                BEGIN(INITIAL);
            } else {
                string_buffer += '\"'; // обычный символ внутри char
            }
          }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 283 "lex.l"
{ lexical_error("Unterminated literal", yytext); BEGIN(INITIAL); }
	YY_BREAK


case 83:
YY_RULE_SETUP
#line 288 "lex.l"
{ string_buffer += '\n'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 289 "lex.l"
{ string_buffer += '\t'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 290 "lex.l"
{ string_buffer += '\r'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 291 "lex.l"
{ string_buffer += '\a'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 292 "lex.l"
{ string_buffer += '\b'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 293 "lex.l"
{ string_buffer += '\f'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 294 "lex.l"
{ string_buffer += '\v'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 295 "lex.l"
{ string_buffer += '\0'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 296 "lex.l"
{ string_buffer += '\''; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 297 "lex.l"
{ string_buffer += '\"'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 298 "lex.l"
{ string_buffer += '\\'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 299 "lex.l"
{ string_buffer += '\?'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 301 "lex.l"
{
             int val = strtol(yytext, NULL, 10);
             if (val > 255) {
               lexical_error("Decimal escape sequence out of range", yytext);
               val = 255;
             }
             string_buffer += (char)val;
             BEGIN(is_char_escape ? CHAR : STRING);
           }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 311 "lex.l"
{
             int val = strtol(yytext + 1, NULL, 8);
             if (val > 255) {
               lexical_error("Octal escape sequence out of range", yytext);
               val = 255;
             }
             string_buffer += (char)val;
             BEGIN(is_char_escape ? CHAR : STRING);
           }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 321 "lex.l"
{
             int val = strtol(yytext + 1, NULL, 16);
             if (val > 255) {
               lexical_error("Hex escape sequence out of range", yytext);
               val = 255;
             }
             string_buffer += (char)val;
             BEGIN(is_char_escape ? CHAR : STRING);
           }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 331 "lex.l"
{
             char c = yytext[1];
             char escaped_char = (c - 'A' + 1);
             string_buffer += escaped_char;
             BEGIN(is_char_escape ? CHAR : STRING);
           }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 338 "lex.l"
{
             lexical_error("Unknown escape sequence", yytext);
             string_buffer += '\\';
             string_buffer += yytext;
             BEGIN(is_char_escape ? CHAR : STRING);
           }
	YY_BREAK

case 100:
YY_RULE_SETUP
#line 346 "lex.l"
{ lexical_error("Unknown symbol", yytext); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 348 "lex.l"
ECHO;
	YY_BREAK
#line 1567 "lex.yy.c"
			case YY_STATE_EOF(STRING):
			case YY_STATE_EOF(CHAR):
			case YY_STATE_EOF(ESCAPE):
			case YY_STATE_EOF(AFTER_KEYWORD):
			case YY_STATE_EOF(FIRST_LINE):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 205 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 205 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 204);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 348 "lex.l"


void push_token(int type, const string& text) {
    cout << "Pushed token: " << type << " -> '" << text << "'" << endl;
    token_queue.push_back({type, text});
    last_pushed_token_type = type;
}

void lexical_error(const char* message, const char* value) {
    cerr << "ERROR (line " << yylineno << "): " << message << ": '" << value << "'" << endl;
}

void place_semicolons(const char* line_text, int first_indent, bool end_of_file_flag) {
    int current_indent = count_last_line_indent(line_text);

    if(current_indent == first_indent) {
        if (last_pushed_token_type != SEMICOLON) {
            push_token(SEMICOLON, ";");
        }
    } 
    else if(current_indent < first_indent && !end_of_file_flag) {
        lexical_error("Indentation without context", line_text);
    }
}

int count_last_line_indent(const char* text) {
    const char* last_line_start = text;
    
    // Находим начало последней строки
    while (*text) {
        if (*text == '\n') {
            last_line_start = text + 1;
        }
        text++;
    }
    
    // Считаем отступ для последней строки
    int indent = 0;
    while (*last_line_start == ' ' || *last_line_start == '\t') {
        if (*last_line_start == '\t') {
            indent += 8;
        } else {
            indent++;
        }
        last_line_start++;
    }
    return indent;
}

bool process_indentation(const char* line_text, vector<int>& layout_stack, bool start_block_flag, bool first_block_indent_flag, bool end_of_file_flag) {
	bool add_indent_flag = false; // флаг для определения необходимости сохранения отступа после "{"
	
	// Если вошли сразу после ключевого слова, то выводим токен с "{"
	if (start_block_flag) {
		push_token(LEFT_BRACE, "{");
		add_indent_flag = true;
		return true;
	} 
	
	int current_indent = count_last_line_indent(line_text); // получаем текущий отступ в строке
	
	//Если отступ меньше отступа остального кода, то выводим ошибку
	if (current_indent < layout_stack[0] && !end_of_file_flag){
		lexical_error("Indentation without context", line_text);
	}
	
	// Если в предыдущем входе в функцию был выведен токен с "{", то сохраняем отступ в стеке
	if(first_block_indent_flag){
		layout_stack.push_back(current_indent);
	}
	
	int last_indent = first_block_indent_flag ? *(layout_stack.rbegin() + 1) : layout_stack.back();
	if(first_block_indent_flag)
	{
		if(current_indent == last_indent && !end_of_file_flag) {
			if(last_pushed_token_type != SEMICOLON) push_token(SEMICOLON, ";");
			push_token(RIGHT_BRACE, "}");
			layout_stack.pop_back();
		}
		else if(current_indent <= last_indent && end_of_file_flag)
		{
			if(last_pushed_token_type != SEMICOLON) push_token(SEMICOLON, ";");
			while (layout_stack.size() > 1 && current_indent <= last_indent) 
			{
				layout_stack.pop_back();
				push_token(RIGHT_BRACE, "}");
				last_indent = layout_stack.back();
			}
		}
		else if(!token_queue.empty() && current_indent > last_indent)
		{
			if(token_queue.back().type != LEFT_BRACE) {
				if(last_pushed_token_type != SEMICOLON) push_token(SEMICOLON, ";");
			}
		}
	}
	else
	{
		if(current_indent == last_indent)
		{
			if(last_pushed_token_type != SEMICOLON) push_token(SEMICOLON, ";");
		}
		else if(current_indent > last_indent)
		{
			lexical_error("Inconsistent indentation in block after key word", line_text);
		}
		else if(current_indent < last_indent || end_of_file_flag)
		{
			if(last_pushed_token_type != SEMICOLON) push_token(SEMICOLON, ";");
			while(layout_stack.size() > 1 && current_indent < last_indent) 
			{
				layout_stack.pop_back();
				push_token(RIGHT_BRACE, "}");
				last_indent = layout_stack.back();
			}
		}
	}
	return(layout_stack.size() > 1);
}

int get_next_token(void) {
    const int SEMICOLON_TYPE = 281;

    if(!token_queue.empty()) {
        if (token_queue.front().type == SEMICOLON_TYPE) {    
            auto it = token_queue.begin() + 1; 
            while (it != token_queue.end() && it->type == SEMICOLON_TYPE) {
                it = token_queue.erase(it);
            }
        }
    }

    if(!token_queue.empty()) {
        Token t = token_queue.front();
        token_queue.pop_front();
        
        yylval.str = _strdup(t.text.c_str()); 
        
        printf("Parser reads token: %d ('%s')\n", t.type, t.text.c_str());
        return(t.type);
    }

    #undef yylex
    int flex_result = yylex(); 
    #define yylex get_next_token 
    
    printf("\nParser calls original yylex, returned %d\n", flex_result);
    
    if(flex_result == 0) {
        if (token_queue.empty()) {
            return(0);
        }
        return(get_next_token());
    }

    if(!token_queue.empty()) {
        return(get_next_token());
    }

    print_token_queue();
    return(flex_result); 
}