/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 102
#define YY_END_OF_BUFFER 103
static yyconst short int yy_acclist[375] =
    {   0,
       10,   10,    1,  103,  101,  102,    4,  101,  102,   45,
      102,    3,  101,  102,  101,  102,   76,  101,  102,   25,
      101,  102,  101,  102,   75,  101,  102,   61,  101,  102,
       62,  101,  102,   33,  101,  102,   31,  101,  102,   67,
      101,  102,   32,  101,  102,   26,  101,  102,   34,  101,
      102,   71,  101,  102,   71,  101,  102,   27,  101,  102,
       68,  101,  102,   36,  101,  102,   28,  101,  102,   37,
      101,  102,   70,  101,  102,   70,  101,  102,   70,  101,
      102,   70,  101,  102,   70,  101,  102,   70,  101,  102,
       70,  101,  102,   63,  101,  102,   29,  101,  102,   64,

      101,  102,   35,  101,  102,   69,  101,  102,   69,  101,
      102,   69,  101,  102,   69,  101,  102,   69,  101,  102,
       69,  101,  102,   69,  101,  102,   69,  101,  102,   69,
      101,  102,   69,  101,  102,   65,  101,  102,   30,  101,
      102,   66,  101,  102,   80,  101,  102,   83,  102,   82,
      101,  102,   81,  101,  102,   79,  101,  102,  100,  101,
      102,  102,   93,  100,  101,  102,   92,  100,  101,  102,
       91,   96,  100,  101,  102,   96,  100,  101,  102,   95,
      100,  101,  102,   94,  100,  101,  102,  100,  101,  102,
       87,  100,  101,  102,   88,  100,  101,  102,   89,  100,

      101,  102,   84,  100,  101,  102,  100,  101,  102,   86,
      100,  101,  102,   85,  100,  101,  102,   90,  100,  101,
      102,  100,  101,  102,   10,  101,  102,    9,  101,  102,
        8,  102,   11,  101,  102,   44,  101,  102,   44,  101,
      102,   44,  102,   43,  101,  102,    2,  101,  102,    1,
        2,  101,  102,    1,  102,    4,   45,   45,    3,   22,
       20,   24,    5,   12,   17,   71,   15,   13,   18,   16,
       14,   19,   70,   70,   70,   70,   70,   70,   70,   70,
       23,   69,   69,   69,   40,   69,   69,   49,   69,   46,
       69,   69,   41,   69,   69,   69,   69,    6,   21,   80,

       77,   96,   99,   97,   98,   10,    9,    8,   11,   11,
        7,   44,   44,   43,   42,    1,    5,   74,   73,   72,
       70,   70,   70,   70,   53,   70,   70,   70,   69,   69,
       69,   38,   69,   69,   69,   69,   78,   58,   70,   55,
       70,   70,   70,   70,   70,   59,   70,   48,   69,   52,
       69,   51,   69,   69,   50,   69,   69,   74,   60,   70,
       57,   70,   70,   70,   69,   39,   69,   70,   56,   70,
       47,   69,   54,   70
    } ;

static yyconst short int yy_accept[209] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        3,    3,    3,    3,    4,    5,    7,   10,   12,   15,
       17,   20,   23,   25,   28,   31,   34,   37,   40,   43,
       46,   49,   52,   55,   58,   61,   64,   67,   70,   73,
       76,   79,   82,   85,   88,   91,   94,   97,  100,  103,
      106,  109,  112,  115,  118,  121,  124,  127,  130,  133,
      136,  139,  142,  145,  148,  150,  153,  156,  159,  162,
      163,  167,  171,  176,  180,  184,  188,  191,  195,  199,
      203,  207,  210,  214,  218,  222,  225,  228,  231,  233,
      236,  239,  242,  244,  247,  250,  254,  256,  257,  257,

      257,  257,  258,  259,  260,  261,  262,  263,  264,  265,
      266,  266,  267,  267,  267,  268,  269,  270,  271,  272,
      273,  274,  275,  276,  277,  278,  279,  280,  281,  282,
      283,  284,  285,  287,  288,  290,  292,  293,  295,  296,
      297,  298,  299,  300,  301,  301,  302,  303,  304,  305,
      306,  307,  308,  309,  310,  311,  312,  313,  314,  315,
      316,  317,  318,  319,  320,  321,  322,  323,  324,  325,
      327,  328,  329,  330,  331,  332,  334,  335,  336,  337,
      338,  338,  340,  342,  343,  344,  345,  346,  348,  350,
      352,  354,  355,  357,  358,  358,  359,  361,  363,  364,

      365,  366,  368,  369,  371,  373,  375,  375
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    1,    8,    1,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   29,   32,   33,
       34,   34,   35,   34,   34,   34,   34,   34,   36,   34,
       34,   34,   37,   38,   34,   34,   34,   39,   34,   34,
       40,   41,   42,   43,   44,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,   54,   54,   55,   54,   56,
       57,   54,   54,   58,   59,   60,   61,   62,   63,   64,
       54,   54,   65,   66,   67,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[68] =
    {   0,
        1,    2,    3,    1,    1,    1,    4,    1,    1,    5,
        1,    1,    1,    1,    1,    6,    1,    1,    7,    7,
        7,    1,    1,    1,    1,    1,    1,    8,    9,    9,
        9,    9,    9,   10,   10,   10,   10,   10,   10,    8,
       11,    8,    8,   10,    7,    7,    7,    7,    7,    7,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,    1,    1,    1
    } ;

static yyconst short int yy_base[223] =
    {   0,
        0,    0,   65,   66,   67,   75,  114,  176,   77,   81,
       84,   89,  470,   93,  472,  474,   97,  120,  124,  464,
      474,  474,  450,  474,  474,  474,  422,  474,  474,   55,
      474,  409,  111,   84,  404,  474,   93,   85,  398,    0,
      365,  367,   93,  356,  346,  347,  474,  474,  474,  361,
        0,  355,   94,  342,   64,  346,  342,  340,  335,  272,
      307,  256,  474,    0,  474,  474,  474,  140,  474,  474,
      474,  474,  146,  171,  474,  474,    0,  474,  474,  474,
      474,  133,  474,  474,  474,    0,    0,  319,  317,   96,
      474,  196,  202,  303,  474,  206,  210,  225,  240,  302,

      299,  244,  248,  252,  474,  474,  474,    0,  474,  474,
      204,  252,  168,    0,  474,  474,  474,  474,  474,  474,
        0,  255,  266,  255,  247,  243,  240,  236,  474,    0,
      234,  232,    0,  225,    0,    0,  214,    0,  210,  217,
      203,  474,  474,    0,  273,  474,  260,  474,  174,    0,
        0,  246,  241,  153,  164,  474,  474,  260,  223,  474,
      280,    0,  267,  239,    0,  182,  177,  170,  173,  167,
      161,  161,  157,  157,  151,    0,  123,  126,  119,  474,
      275,    0,    0,  124,  101,  107,  100,    0,    0,    0,
        0,   88,    0,   88,  281,  287,    0,    0,   70,   64,

       34,    0,   30,    0,    0,    0,  474,  325,  337,  349,
      361,  373,  381,  389,  401,  406,  411,  420,  432,  444,
      456,  462
    } ;

static yyconst short int yy_def[223] =
    {   0,
      207,    1,  208,  208,  208,  208,  209,  209,  210,  210,
      211,  211,  212,  212,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  213,
      213,  213,  213,  213,  213,  213,  207,  207,  207,  207,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      207,  207,  207,  215,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  216,  207,  207,  207,
      207,  207,  207,  207,  207,  217,  218,  207,  207,  219,
      207,  220,  220,  207,  207,  207,  207,  207,  207,  207,

      207,  207,  207,  207,  207,  207,  207,  221,  207,  207,
      207,  207,  207,  222,  207,  207,  207,  207,  207,  207,
      213,  213,  213,  213,  213,  213,  213,  213,  207,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  207,  207,  215,  207,  207,  207,  207,  207,  217,
      218,  207,  207,  219,  219,  207,  207,  220,  207,  207,
      207,  221,  207,  207,  222,  213,  213,  213,  213,  213,
      213,  213,  214,  214,  214,  214,  214,  214,  214,  207,
      207,  213,  213,  213,  213,  213,  213,  213,  214,  214,
      214,  214,  214,  214,  207,  207,  213,  213,  213,  213,

      214,  214,  213,  213,  214,  213,    0,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207
    } ;

static yyconst short int yy_nxt[542] =
    {   0,
       16,   17,   18,   16,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       34,   35,   36,   37,   38,   39,   16,   16,   40,   41,
       42,   40,   43,   40,   44,   40,   45,   46,   40,   47,
       48,   49,   50,   51,   51,   51,   52,   53,   54,   51,
       51,   51,   55,   51,   56,   51,   57,   58,   51,   59,
       51,   51,   60,   51,   61,   62,   63,   65,   65,   65,
      108,   66,   66,   66,   67,   67,   67,   65,   88,   89,
      109,   66,   88,   89,   67,   92,   93,  206,   92,  205,
       92,   93,   90,   92,   96,   97,   90,   96,   98,   99,

      111,   99,  112,  112,  112,   68,   68,   68,  116,  118,
      119,  155,  100,  135,  204,   68,   70,  117,  203,  136,
       71,  102,  103,   72,  102,   99,   99,  111,  104,  112,
      112,  112,   73,   74,   74,  100,  202,  124,  132,  100,
       75,  145,  145,  145,  145,  201,  113,  125,   94,  114,
      133,  149,  149,   94,   76,  200,   77,  199,   78,   79,
      198,  101,  156,   80,  147,  147,  147,  113,  207,   81,
       82,   83,  197,   84,  114,   85,  194,   86,   70,  155,
      146,  193,   71,  192,  101,   72,  164,  164,  101,  147,
      147,  147,  149,  149,   73,   74,   74,  158,  158,  191,

      158,  190,   75,  158,  158,  189,  158,  161,  161,  188,
      161,  161,  161,  187,  161,  186,   76,  185,   77,  207,
       78,   79,  163,  163,  163,   80,   98,   99,  184,   99,
      156,   81,   82,   83,  183,   84,  182,   85,  160,   86,
      100,   99,   99,  153,   99,  102,  102,  152,  102,  102,
      103,  179,  102,   99,   99,  100,  104,  164,  164,  100,
      159,  158,  158,  100,  158,  178,  159,  100,  111,  177,
      112,  112,  112,  176,  145,  145,  145,  145,  147,  147,
      147,  161,  161,  175,  161,  163,  163,  163,  195,  101,
      195,  174,  173,  196,  196,  196,  172,  171,  181,  196,

      196,  196,  170,  169,  101,  196,  196,  196,  101,  168,
      167,  166,  101,  180,  142,  181,  101,  108,  160,  153,
      152,  143,  142,  141,  159,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,  121,  140,  121,  139,  121,
      121,  138,  121,  130,  137,  130,  134,  130,  130,  131,

      130,  144,  144,  129,  128,  127,  144,  144,  144,  144,
      144,  126,  144,  148,  148,  148,  148,  150,  123,  150,
      151,  122,  120,  151,  151,  115,  151,  151,  151,  151,
      151,  151,  154,  110,  107,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  162,  162,  106,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  165,  105,
      165,  207,   70,   15,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,

      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207
    } ;

static yyconst short int yy_chk[542] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    5,
       30,    3,    4,    5,    3,    4,    5,    6,    9,    9,
       30,    6,   10,   10,    6,   11,   11,  203,   11,  201,
       12,   12,    9,   12,   14,   14,   10,   14,   17,   17,

       34,   17,   34,   34,   34,    3,    4,    5,   37,   38,
       38,   90,   17,   55,  200,    6,    7,   37,  199,   55,
        7,   18,   18,    7,   18,   19,   19,   33,   19,   33,
       33,   33,    7,    7,    7,   18,  194,   43,   53,   19,
        7,   68,   68,   68,   68,  192,   33,   43,   11,   33,
       53,   82,   82,   12,    7,  187,    7,  186,    7,    7,
      185,   17,   90,    7,   73,   73,   73,   33,  154,    7,
        7,    7,  184,    7,   33,    7,  179,    7,    8,  155,
       68,  178,    8,  177,   18,    8,  113,  113,   19,   74,
       74,   74,  149,  149,    8,    8,    8,   92,   92,  175,

       92,  174,    8,   93,   93,  173,   93,   96,   96,  172,
       96,   97,   97,  171,   97,  170,    8,  169,    8,  154,
        8,    8,  111,  111,  111,    8,   98,   98,  168,   98,
      155,    8,    8,    8,  167,    8,  166,    8,  159,    8,
       98,   99,   99,  153,   99,  102,  102,  152,  102,  103,
      103,  141,  103,  104,  104,   99,  104,  164,  164,  102,
       92,  158,  158,  103,  158,  140,   93,  104,  112,  139,
      112,  112,  112,  137,  145,  145,  145,  145,  147,  147,
      147,  161,  161,  134,  161,  163,  163,  163,  181,   98,
      181,  132,  131,  181,  181,  181,  128,  127,  163,  195,

      195,  195,  126,  125,   99,  196,  196,  196,  102,  124,
      123,  122,  103,  145,  101,  163,  104,  100,   94,   89,
       88,   62,   61,   60,  158,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  211,  211,  211,  211,  211,  211,  211,  211,  211,
      211,  211,  211,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  213,   59,  213,   58,  213,
      213,   57,  213,  214,   56,  214,   54,  214,  214,   52,

      214,  215,  215,   50,   46,   45,  215,  215,  215,  215,
      215,   44,  215,  216,  216,  216,  216,  217,   42,  217,
      218,   41,   39,  218,  218,   35,  218,  218,  218,  218,
      218,  218,  219,   32,   27,  219,  219,  219,  219,  219,
      219,  219,  219,  219,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  221,  221,   23,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  222,   20,
      222,   15,   13,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,

      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#define INITIAL 0
#line 2 "lex.l"
#include <iostream>
#include <stack>
#include <vector>
#include <string>
#include <cstdlib>
#include <cstdio>
#include <deque>
#include "token_queue.h"
#include "parser.tab.h"

using namespace std;

int last_pushed_token_type;
void push_token(int type, const string& text);
void lexical_error(const char* message, const char* value);
int count_last_line_indent(const char* text); 
bool process_indentation(const char* line_text, vector<int>& layout_stack, bool start_block_flag, bool first_block_indent_flag, bool end_of_file_flag);
void place_semicolons(const char* line_text, int first_indent, bool end_of_file_flag);
#define STRING 1
#define CHAR 2
#define ESCAPE 3
#define MULTILINE_COMMENT 4
#define AFTER_KEYWORD 5
#define FIRST_LINE 6

#define YY_NEVER_INTERACTIVE 1
#line 639 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 39 "lex.l"



string string_buffer;        // для строковых литералов
bool is_char_escape;         // флаг для определения типа escape-последовательности
bool char_processed = false; // для отслеживания обработки char
vector<int> layout_stack = {0};   // стек с количествами отступов  
bool indent_process_flag = false; // флаг обработки отступов в блоках
int first_indent = 0;		          // количество отступов первой строки
bool first_line_flag = true;      // флаг необходимости обработки первой строки отдельно
int brace_count = 0;		          // счетчик для баланса фигурных скобок
bool first_block_indent_flag = false;
bool custom_indents_in_block_flag = false; // флаг пропуска блока с пользовательскими отступами
int comment_counter;	     // счетчик для комментариев
bool newline_flag = false; // флаг, указывающий на наличие переносов строк в многострочном комментарии
bool comment_after_kw_flag = false; // флаг, показывающий, что после ключевого слова был обнаружен многострочный комментарий


	/* Проверяем, находимся ли мы в начале файла */
	if (first_line_flag) {
		first_line_flag = false;
		BEGIN(FIRST_LINE);
	}
	
#line 818 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 208 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 474 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */

case 1:
YY_RULE_SETUP
#line 64 "lex.l"
{ first_indent = count_last_line_indent(yytext); 
				  BEGIN(INITIAL); 
				}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 68 "lex.l"
{ 
				yyless(0);
				first_indent = 0;
				BEGIN(INITIAL);
				}
	YY_BREAK

case 3:
YY_RULE_SETUP
#line 75 "lex.l"
{ /* Пропускаем пробелы */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 76 "lex.l"
{  /* Пропускаем табы */ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 78 "lex.l"
{ /* Однострочный комментарий */}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 81 "lex.l"
{ 
                  // Начало многострочного комментария
                  comment_counter = 0;
                  comment_counter += strlen(yytext);
                  BEGIN(MULTILINE_COMMENT);
                }
	YY_BREAK

case 7:
YY_RULE_SETUP
#line 89 "lex.l"
{ 
                  comment_counter += strlen(yytext);
				  for (int i = 0; i < comment_counter; i++) {
					unput(' ');
					}
				  if(newline_flag){
					unput('\n');
					newline_flag = false;
				  }
				  if(comment_after_kw_flag){
					BEGIN(AFTER_KEYWORD);
				  } else {
                    BEGIN(INITIAL);
				  }
                }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 105 "lex.l"
{ comment_counter = 0; newline_flag = true;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 106 "lex.l"
{ comment_counter += strlen(yytext)*4; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 108 "lex.l"
{ comment_counter += strlen(yytext); } 
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 109 "lex.l"
{ comment_counter += strlen(yytext); }
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 111 "lex.l"
{ 
				  comment_counter = 0;
                  lexical_error("Unterminated multiline comment", yytext);
			      BEGIN(INITIAL);
                }
	YY_BREAK

case 12:
YY_RULE_SETUP
#line 118 "lex.l"
{ push_token(RIGHT_ARROW, yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 119 "lex.l"
{ push_token(LEFT_ARROW, yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 120 "lex.l"
{ push_token(FAT_ARROW, yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 121 "lex.l"
{ push_token(DOUBLE_COLON, yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 122 "lex.l"
{ push_token(DOUBLE_EQUALS, yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 123 "lex.l"
{ push_token(NOT_EQUALS, yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 124 "lex.l"
{ push_token(LESS_EQUAL, yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 125 "lex.l"
{ push_token(GREATER_EQUAL, yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 126 "lex.l"
{ push_token(DOUBLE_AMPERSAND, yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 127 "lex.l"
{ push_token(DOUBLE_PIPE, yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 128 "lex.l"
{ push_token(DOUBLE_BANG, yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 129 "lex.l"
{ push_token(DOUBLE_CARET, yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 130 "lex.l"
{ push_token(DOUBLE_ASTERISK, yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 131 "lex.l"
{ push_token(DOLLAR, yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 132 "lex.l"
{ push_token(DOT, yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 133 "lex.l"
{ push_token(COLON, yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 134 "lex.l"
{ push_token(EQUALS, yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 135 "lex.l"
{ push_token(BACKSLASH, yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 136 "lex.l"
{ push_token(PIPE, yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 137 "lex.l"
{ push_token(PLUS, yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 138 "lex.l"
{ push_token(MINUS, yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 139 "lex.l"
{ push_token(ASTERISK, yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 140 "lex.l"
{ push_token(SLASH, yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 141 "lex.l"
{ push_token(CARET, yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 142 "lex.l"
{ push_token(LESS, yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 143 "lex.l"
{ push_token(GREATER, yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 145 "lex.l"
{ push_token(KW_LET, yytext); BEGIN(AFTER_KEYWORD);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 146 "lex.l"
{ push_token(KW_WHERE, yytext); BEGIN(AFTER_KEYWORD);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 147 "lex.l"
{ push_token(KW_DO, yytext); BEGIN(AFTER_KEYWORD);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 148 "lex.l"
{ push_token(KW_OF, yytext); BEGIN(AFTER_KEYWORD);}
	YY_BREAK

case 42:
YY_RULE_SETUP
#line 151 "lex.l"
{ 
                  // Начало многострочного комментария
                  comment_counter = 0;
                  comment_counter += strlen(yytext);
				  comment_after_kw_flag = true;
                  BEGIN(MULTILINE_COMMENT);
                }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 159 "lex.l"
{
				 comment_after_kw_flag = false;
				 yyless(0);
				 indent_process_flag = false;
				 custom_indents_in_block_flag = true;
				 BEGIN(INITIAL);
				}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 166 "lex.l"
{
                 comment_after_kw_flag = false;
				 yyless(0);
				 indent_process_flag = true;
				 custom_indents_in_block_flag = false;
				 process_indentation(yytext, layout_stack, true, first_block_indent_flag, false);
				 first_block_indent_flag = true;
				 BEGIN(INITIAL);
				}
	YY_BREAK

case 45:
YY_RULE_SETUP
#line 177 "lex.l"
{
				if (indent_process_flag && !custom_indents_in_block_flag){
					indent_process_flag = process_indentation(yytext, layout_stack, false, first_block_indent_flag, false);
					first_block_indent_flag = false;
				} else if (!custom_indents_in_block_flag){
					place_semicolons(yytext, first_indent, false);
				}
            }
	YY_BREAK

case YY_STATE_EOF(INITIAL):
#line 187 "lex.l"
{
				if (indent_process_flag && !custom_indents_in_block_flag){
					while (indent_process_flag){
						indent_process_flag = process_indentation(yytext, layout_stack, false, first_block_indent_flag, true);
						first_block_indent_flag = false;
					}
				} else if (!custom_indents_in_block_flag){
					place_semicolons(yytext, first_indent, true);
				}
				
				if (brace_count != 0){
					lexical_error("Mismatched brackets", yytext);
				}
				return 0;
           }
	YY_BREAK

case 46:
YY_RULE_SETUP
#line 204 "lex.l"
{ push_token(KW_IN, yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 205 "lex.l"
{ push_token(KW_RETURN, yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 206 "lex.l"
{ push_token(KW_CASE, yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 207 "lex.l"
{ push_token(KW_IF, yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 208 "lex.l"
{ push_token(KW_THEN, yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 209 "lex.l"
{ push_token(KW_ELSE, yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 210 "lex.l"
{ push_token(KW_DATA, yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 212 "lex.l"
{ push_token(KW_INT, yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 213 "lex.l"
{ push_token(KW_INT, yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 214 "lex.l"
{ push_token(KW_CHAR, yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 215 "lex.l"
{ push_token(KW_STRING, yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 216 "lex.l"
{ push_token(KW_FLOAT, yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 217 "lex.l"
{ push_token(KW_BOOL, yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 218 "lex.l"
{ push_token(KW_TRUE, yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 219 "lex.l"
{ push_token(KW_FALSE, yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 221 "lex.l"
{ push_token(LEFT_PAREN, yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 222 "lex.l"
{ push_token(RIGHT_PAREN, yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 223 "lex.l"
{ push_token(LEFT_BRACKET, yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 224 "lex.l"
{ push_token(RIGHT_BRACKET, yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 225 "lex.l"
{ 
                 brace_count++;
                 push_token(LEFT_BRACE, yytext);
               }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 229 "lex.l"
{ 
                 brace_count--;
				 if (brace_count == 0){
					custom_indents_in_block_flag = false;
				 }
                 push_token(RIGHT_BRACE, yytext);
               }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 236 "lex.l"
{ push_token(COMMA, yytext); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 237 "lex.l"
{ if (last_pushed_token_type != SEMICOLON) push_token(SEMICOLON, yytext); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 239 "lex.l"
{ push_token(ID, yytext); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 240 "lex.l"
{ push_token(ID_CAP, yytext); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 242 "lex.l"
{ push_token(DEC_LITERAL, yytext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 243 "lex.l"
{ push_token(HEX_LITERAL, yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 244 "lex.l"
{ push_token(OCT_LITERAL, yytext+2); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 245 "lex.l"
{ push_token(FLOAT, yytext); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 247 "lex.l"
{ string_buffer.clear(); is_char_escape = true; BEGIN(CHAR); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 248 "lex.l"
{ string_buffer.clear(); is_char_escape = false; BEGIN(STRING); }
	YY_BREAK

case 77:
YY_RULE_SETUP
#line 251 "lex.l"
{
				/* Экранированный бекслеш */
				string_buffer += '\\';
			}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 256 "lex.l"
{
						/* Haskell string gap: backslash + whitespace 
						(включая перевод строки) + backslash */
						/* Игнорируем — ничего не добавляем в строку */
					}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 262 "lex.l"
{ BEGIN(ESCAPE); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 264 "lex.l"
{ string_buffer += yytext; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 266 "lex.l"
{ 
            if (is_char_escape) {
                if (string_buffer.size() != 1) 
                    lexical_error("Invalid char literal length", string_buffer.c_str());
                push_token(CHAR_LITERAL, string_buffer);
                string_buffer.clear();
                BEGIN(INITIAL);
            } else {
                string_buffer += '\''; // обычный символ внутри строки
            }
          }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 278 "lex.l"
{ 
            if (!is_char_escape) {
                push_token(STRING_LITERAL, string_buffer);
                string_buffer.clear();
                BEGIN(INITIAL);
            } else {
                string_buffer += '\"'; // обычный символ внутри char
            }
          }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 288 "lex.l"
{ lexical_error("Unterminated literal", yytext); BEGIN(INITIAL); }
	YY_BREAK


case 84:
YY_RULE_SETUP
#line 293 "lex.l"
{ string_buffer += '\n'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 294 "lex.l"
{ string_buffer += '\t'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 295 "lex.l"
{ string_buffer += '\r'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 296 "lex.l"
{ string_buffer += '\a'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 297 "lex.l"
{ string_buffer += '\b'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 298 "lex.l"
{ string_buffer += '\f'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 299 "lex.l"
{ string_buffer += '\v'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 300 "lex.l"
{ string_buffer += '\0'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 301 "lex.l"
{ string_buffer += '\''; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 302 "lex.l"
{ string_buffer += '\"'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 303 "lex.l"
{ string_buffer += '\\'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 304 "lex.l"
{ string_buffer += '\?'; BEGIN(is_char_escape ? CHAR : STRING); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 306 "lex.l"
{
             int val = strtol(yytext, NULL, 10);
             if (val > 255) {
               lexical_error("Decimal escape sequence out of range", yytext);
               val = 255;
             }
             string_buffer += (char)val;
             BEGIN(is_char_escape ? CHAR : STRING);
           }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 316 "lex.l"
{
             int val = strtol(yytext + 1, NULL, 8);
             if (val > 255) {
               lexical_error("Octal escape sequence out of range", yytext);
               val = 255;
             }
             string_buffer += (char)val;
             BEGIN(is_char_escape ? CHAR : STRING);
           }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 326 "lex.l"
{
             int val = strtol(yytext + 1, NULL, 16);
             if (val > 255) {
               lexical_error("Hex escape sequence out of range", yytext);
               val = 255;
             }
             string_buffer += (char)val;
             BEGIN(is_char_escape ? CHAR : STRING);
           }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 336 "lex.l"
{
             char c = yytext[1];
             char escaped_char = (c - 'A' + 1);
             string_buffer += escaped_char;
             BEGIN(is_char_escape ? CHAR : STRING);
           }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 343 "lex.l"
{
             lexical_error("Unknown escape sequence", yytext);
             string_buffer += '\\';
             string_buffer += yytext;
             BEGIN(is_char_escape ? CHAR : STRING);
           }
	YY_BREAK

case 101:
YY_RULE_SETUP
#line 351 "lex.l"
{ lexical_error("Unknown symbol", yytext); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 353 "lex.l"
ECHO;
	YY_BREAK
#line 1578 "lex.yy.c"
			case YY_STATE_EOF(STRING):
			case YY_STATE_EOF(CHAR):
			case YY_STATE_EOF(ESCAPE):
			case YY_STATE_EOF(AFTER_KEYWORD):
			case YY_STATE_EOF(FIRST_LINE):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 208 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 208 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 207);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 353 "lex.l"


void push_token(int type, const string& text) {
    cout << "Pushed token: " << type << " -> '" << text << "'" << endl;
    token_queue.push_back({type, text});
    last_pushed_token_type = type;
}

void lexical_error(const char* message, const char* value) {
    cerr << "ERROR (line " << yylineno << "): " << message << ": '" << value << "'" << endl;
}

void place_semicolons(const char* line_text, int first_indent, bool end_of_file_flag) {
    int current_indent = count_last_line_indent(line_text);

    if(current_indent == first_indent) {
        if (last_pushed_token_type != SEMICOLON) {
            push_token(SEMICOLON, ";");
        }
    } 
    else if(current_indent < first_indent && !end_of_file_flag) {
        lexical_error("Indentation without context", line_text);
    }
}

int count_last_line_indent(const char* text) {
    const char* last_line_start = text;
    
    // Находим начало последней строки
    while (*text) {
        if (*text == '\n') {
            last_line_start = text + 1;
        }
        text++;
    }
    
    // Считаем отступ для последней строки
    int indent = 0;
    while (*last_line_start == ' ' || *last_line_start == '\t') {
        if (*last_line_start == '\t') {
            indent += 4;
        } else {
            indent++;
        }
        last_line_start++;
    }
    return indent;
}

bool process_indentation(const char* line_text, vector<int>& layout_stack, bool start_block_flag, bool first_block_indent_flag, bool end_of_file_flag) {
	bool add_indent_flag = false; // флаг для определения необходимости сохранения отступа после "{"
	
	// Если вошли сразу после ключевого слова, то выводим токен с "{"
	if (start_block_flag) {
		push_token(LEFT_BRACE, "{");
		add_indent_flag = true;
		return true;
	} 
	
	int current_indent = count_last_line_indent(line_text); // получаем текущий отступ в строке
	
	//Если отступ меньше отступа остального кода, то выводим ошибку
	if (current_indent < layout_stack[0] && !end_of_file_flag){
		lexical_error("Indentation without context", line_text);
	}
	
	// Если в предыдущем входе в функцию был выведен токен с "{", то сохраняем отступ в стеке
	if(first_block_indent_flag){
		layout_stack.push_back(current_indent);
	}
	
	int last_indent = first_block_indent_flag ? *(layout_stack.rbegin() + 1) : layout_stack.back();
	if(first_block_indent_flag)
	{
		if(current_indent == last_indent && !end_of_file_flag) {
			if(last_pushed_token_type != SEMICOLON) push_token(SEMICOLON, ";");
			push_token(RIGHT_BRACE, "}");
			layout_stack.pop_back();
		}
		else if(current_indent <= last_indent && end_of_file_flag)
		{
			if(last_pushed_token_type != SEMICOLON) push_token(SEMICOLON, ";");
			while (layout_stack.size() > 1 && current_indent <= last_indent) 
			{
				layout_stack.pop_back();
				push_token(RIGHT_BRACE, "}");
				last_indent = layout_stack.back();
			}
		}
		else if(!token_queue.empty() && current_indent > last_indent)
		{
			if(token_queue.back().type != LEFT_BRACE) {
				if(last_pushed_token_type != SEMICOLON) push_token(SEMICOLON, ";");
			}
		}
	}
	else
	{
		if(current_indent == last_indent)
		{
			if(last_pushed_token_type != SEMICOLON) push_token(SEMICOLON, ";");
		}
		else if(current_indent > last_indent)
		{
			lexical_error("Inconsistent indentation in block after key word", line_text);
		}
		else if(current_indent < last_indent || end_of_file_flag)
		{
			if(last_pushed_token_type != SEMICOLON) push_token(SEMICOLON, ";");
			while(layout_stack.size() > 1 && current_indent < last_indent) 
			{
				layout_stack.pop_back();
				push_token(RIGHT_BRACE, "}");
				last_indent = layout_stack.back();
			}
		}
	}
	return(layout_stack.size() > 1);
}

int get_next_token(void) {
    const int SEMICOLON_TYPE = 281;

    if(!token_queue.empty()) {
        if (token_queue.front().type == SEMICOLON_TYPE) {    
            auto it = token_queue.begin() + 1; 
            while (it != token_queue.end() && it->type == SEMICOLON_TYPE) {
                it = token_queue.erase(it);
            }
        }
    }

    if(!token_queue.empty()) {
        Token t = token_queue.front();
        token_queue.pop_front();
        
        yylval.str = _strdup(t.text.c_str()); 
        
        printf("Parser reads token: %d ('%s')\n", t.type, t.text.c_str());
        return(t.type);
    }

    #undef yylex
    int flex_result = yylex(); 
    #define yylex get_next_token 
    
    printf("\nParser calls original yylex, returned %d\n", flex_result);
    
    if(flex_result == 0) {
        if (token_queue.empty()) {
            return(0);
        }
        return(get_next_token());
    }

    if(!token_queue.empty()) {
        return(get_next_token());
    }

    print_token_queue();
    return(flex_result); 
}
